### ISSUE TITLE
Does this support the Slack Attachments API?

### ISSUE THREAD

**Issue by spicycode** [github/chatops-controller#33]
Also, do we have any examples for using `title`/`title_link` and the other fields it supports?  I'm trying to port a custom slack command over to this at present.

**Comment by mistydemeo** [comment]
Sorry for the late reply!

This doesn't currently support the Slack attachments API. The goal is to be agnostic to what chat system it's communicating with; I'm not sure what the right way would be to expose Slack attachments without tying chatops to Slack specifically.
