### ISSUE TITLE
Release version 3.2.0

### ISSUE THREAD

**Issue by TwP** [github/chatops-controller#42]
@mistydemeo would you be willing to push up version 3.2.0 to rubygems. I do not have permission there to release this gem. Thank you :bowing_man:

**Comment by mistydemeo** [comment]
I think I'm going to bump this to 4.0.0, since the parameter security change is breaking and it would be good to make sure downstream developers are aware of that. 😄

**Comment by mistydemeo** [comment]
4.0.0 is out: https://rubygems.org/gems/chatops-controller/versions/4.0.0
